In [1]:
import pandas as pd

In [2]:
movie=pd.read_csv("movies.csv")

In [3]:
movie.head(12)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.batmanvsupermandawnofjustice.com/,209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-23,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004
10,270000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.superman.com,1452,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Superman Returns,Superman returns to discover his 5-year absenc...,57.925623,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2006-06-28,391081192,154.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Superman Returns,5.4,1400
11,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://www.mgm.com/view/movie/234/Quantum-of-S...,10764,"[{""id"": 627, ""name"": ""killing""}, {""id"": 1568, ...",en,Quantum of Solace,Quantum of Solace continues the adventures of ...,107.928811,"[{""name"": ""Eon Productions"", ""id"": 7576}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2008-10-30,586090727,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965

In [4]:
credits=pd.read_csv("credits.csv")

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

# Data Processing

In [6]:
df = movie.merge(credits,on='title')

In [7]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,movie_id
count,4.809000e+03,4809.000000,4809.000000,4.809000e+03,4807.000000,4809.000000,4809.000000,4809.000000
mean,2.902780e+07,57120.571429,21.491664,8.227511e+07,106.882255,6.092514,690.331670,57120.571429
std,4.070473e+07,88653.369849,31.803366,1.628379e+08,22.602535,1.193989,1234.187111,88653.369849
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,5.000000
25%,7.800000e+05,9012.000000,4.667230,0.000000e+00,94.000000,5.600000,54.000000,9012.000000
50%,1.500000e+07,14624.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000,14624.000000
75%,4.000000e+07,58595.000000,28.350529,9.291317e+07,118.000000,6.800000,737.000000,58595.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000,459488.000000

In [8]:
df.shape

(4809, 23)

In [9]:
df = df[['movie_id','title','overview','genres','keywords','cast','crew']]

In [10]:
df

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [11]:
df.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [12]:
df.dropna(inplace=True) #this is used to remove movies which have null values

In [13]:
import ast

In [14]:
def convert(obj):
    l=[i['name'] for i in ast.literal_eval(obj) ]
    return l

In [15]:
df['genres']=df['genres'].apply(convert)

In [16]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
df['keywords']=df['keywords'].apply(convert)

In [18]:
def convert3(obj):
    l=[]
    c=0
    for i in ast.literal_eval(obj):
        l.append(i['character'])
        c+=1
        if(c==3):
            break
    return l

In [19]:
df['cast']=df['cast'].apply(convert3)

In [20]:
def fatch_director(obj):
    l=[i['name'] for i in ast.literal_eval(obj) if i['department']=='Directing']
    return l

In [21]:
df['crew']=df['crew'].apply(fatch_director)

In [23]:
df['crew'][0]

['James Cameron']

In [24]:
df['overview']=df['overview'].apply(lambda x:x.split())

In [25]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Jake Sully, Neytiri, Dr. Grace Augustine]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain Jack Sparrow, Will Turner, Elizabeth ...","[Gore Verbinski, Pamela Alch, Sharron Reynolds..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[James Bond, Blofeld, Madeleine]","[Sam Mendes, Jayne-Ann Tenggren, Nicoletta Man..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Bruce Wayne / Batman, Alfred Pennyworth, Jame...","[Christopher Nolan, Steve Gehrke, Matthew Reed..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John Carter, Dejah Thoris, Sola]","[Andrew Stanton, Annie Penn, Tommy Gormley, Be..."

In [35]:
def rem_space(obj):
    return [i.replace(" ","") for i in obj]

In [38]:
df['genres'] =df['genres'].apply(rem_space)
df['cast'] =df['cast'].apply(rem_space)
df['crew'] =df['crew'].apply(rem_space)
df['keywords'] =df['keywords'].apply(rem_space)

In [39]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[JakeSully, Neytiri, Dr.GraceAugustine]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[CaptainJackSparrow, WillTurner, ElizabethSwann]","[GoreVerbinski, PamelaAlch, SharronReynolds, K..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[JamesBond, Blofeld, Madeleine]","[SamMendes, Jayne-AnnTenggren, NicolettaMani, ..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[BruceWayne/Batman, AlfredPennyworth, JamesGor...","[ChristopherNolan, SteveGehrke, MatthewReedy, ..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[JohnCarter, DejahThoris, Sola]","[AndrewStanton, AnniePenn, TommyGormley, BenDi..."

In [41]:
df['tags']=df['overview']+df['genres']+df['keywords']+df['cast']+df['crew']
df.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[JakeSully, Neytiri, Dr.GraceAugustine]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[CaptainJackSparrow, WillTurner, ElizabethSwann]","[GoreVerbinski, PamelaAlch, SharronReynolds, K...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[JamesBond, Blofeld, Madeleine]","[SamMendes, Jayne-AnnTenggren, NicolettaMani, ...","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[BruceWayne/Batman, AlfredPennyworth, JamesGor...","[ChristopherNolan, SteveGehrke, MatthewReedy, ...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[JohnCarter, DejahThoris, Sola]","[AndrewStanton, AnniePenn, TommyGormley, BenDi...","[John, Carter, is, a, war-weary,, former, mili..."

In [43]:
new_df=df[['movie_id','title','tags']] # creating a new dataframe which consits mov_id,title ana tags

In [52]:
 new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x)) #making string from list

C:\Users\singh\AppData\Local\Temp\ipykernel_13196\1033127588.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x)) #making string from list

In [53]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [54]:
new_df['tags']=new_df['tags'].apply(lambda x: x.lower()) #converting text of tags in lowercase to make easy for recomandation system

C:\Users\singh\AppData\Local\Temp\ipykernel_13196\2543325826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x: x.lower())

In [55]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d jakesully neytiri dr.graceaugustine jamescameron'

Given the possibility that in these tags, 'love,' 'loving,' and 'loved' may be treated as distinct words, it is necessary to equate them to their root term, 'love.'"

In [87]:
import nltk
from nltk.stem.porter import PorterStemmer 
ps=PorterStemmer()

In [88]:
def stem(text):
    y = [ps.stem(word) for word in text.split()]
    return " ".join(y)

In [90]:
new_df['tags']= new_df['tags'].apply(stem)

C:\Users\singh\AppData\Local\Temp\ipykernel_13196\3021978705.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']= new_df['tags'].apply(stem)

# Vactorisation

In [91]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english',max_features=5000)
vector = tfidf.fit_transform(new_df['tags']).toarray()

In [92]:
vector[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [93]:
vector.shape

(4806, 5000)

In [94]:
tfidf.get_feature_names_out() #this is used to get that 5000 words from vector

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [98]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)
similarity.shape

(4806, 4806)

In [96]:
similarity

array([[1.        , 0.02279265, 0.0310096 , ..., 0.02405431, 0.        ,
        0.        ],
       [0.02279265, 1.        , 0.01271386, ..., 0.0170161 , 0.        ,
        0.00660974],
       [0.0310096 , 0.01271386, 1.        , ..., 0.01607816, 0.        ,
        0.        ],
       ...,
       [0.02405431, 0.0170161 , 0.01607816, ..., 1.        , 0.0179878 ,
        0.02939614],
       [0.        , 0.        , 0.        , ..., 0.0179878 , 1.        ,
        0.01958156],
       [0.        , 0.00660974, 0.        , ..., 0.02939614, 0.01958156,
        1.        ]])

# Main function

In [100]:
list(enumerate(similarity[0]))
        #enumerate function gives tuple of index with its value

[(0, 1.0),
 (1, 0.02279264997957095),
 (2, 0.031009602195740255),
 (3, 0.03630179730081483),
 (4, 0.11376080869104406),
 (5, 0.04485057764800514),
 (6, 0.016249413403768103),
 (7, 0.08015810681366858),
 (8, 0.018725602890684884),
 (9, 0.022689291261803912),
 (10, 0.02917973269177495),
 (11, 0.035697074073843094),
 (12, 0.02681918879462687),
 (13, 0.007685942564347924),
 (14, 0.04497736221897039),
 (15, 0.01750912420531274),
 (16, 0.019924770828259542),
 (17, 0.07230774122062049),
 (18, 0.06408816226816437),
 (19, 0.026812626954407733),
 (20, 0.039981962578473744),
 (21, 0.04406101965069727),
 (22, 0.01794245316405359),
 (23, 0.02675964318794688),
 (24, 0.012659420208088062),
 (25, 0.04955087452450061),
 (26, 0.07589107893799629),
 (27, 0.10573152078409342),
 (28, 0.04697412963742786),
 (29, 0.02256546888698071),
 (30, 0.01855300192548727),
 (31, 0.0746653595682626),
 (32, 0.03819391014929258),
 (33, 0.021764341960281382),
 (34, 0.0),
 (35, 0.026486038954202713),
 (36, 0.10544102740116396),
 (37, 0.033644774123104626),
 (38, 0.03234066145126316),
 (39, 0.021633160442876845),
 (40, 0.025368158981393323),
 (41, 0.09186072552691396),
 (42, 0.0),
 (43, 0.04558931065047724),
 (44, 0.0075723597297011735),
 (45, 0.03573098444981772),
 (46, 0.05032325117708164),
 (47, 0.13650034843208517),
 (48, 0.03646683975443207),
 (49, 0.03188432733319867),
 (50, 0.03385098418312859),
 (51, 0.0416195159259203),
 (52, 0.11792026633780456),
 (53, 0.008861480305129357),
 (54, 0.0082465741822325),
 (55, 0.027581470447613363),
 (56, 0.0759523516976472),
 (57, 0.021906945590818357),
 (58, 0.02677263855169936),
 (59, 0.031594612833489015),
 (60, 0.01918815311696714),
 (61, 0.11556819933520474),
 (62, 0.021156661984306824),
 (63, 0.03665695001852539),
 (64, 0.010410166931727952),
 (65, 0.0032202653209919834),
 (66, 0.0060732822313610615),
 (67, 0.0969621190099468),
 (68, 0.04930649636776105),
 (69, 0.01655946473208373),
 (70, 0.045571913277711734),
 (71, 0.02383098657283711),
 (72, 0.048295704507855614),
 (73, 0.013421945917606233),
 (74, 0.13413457161907666),
 (75, 0.11767385348917703),
 (76, 0.019463386501176204),
 (77, 0.010859375212415468),
 (78, 0.01582516073938747),
 (79, 0.017289264365676307),
 (80, 0.022007676282518415),
 (81, 0.04804839158678116),
 (82, 0.03147836098636063),
 (83, 0.10957666023363913),
 (84, 0.05538905563150515),
 (85, 0.06356499334754254),
 (86, 0.03009730654032355),
 (87, 0.058712656193712395),
 (88, 0.0368172617622386),
 (89, 0.03221276559535552),
 (90, 0.017467596571343606),
 (91, 0.08658119489935909),
 (92, 0.025837799093102434),
 (93, 0.02828099797559452),
 (94, 0.0700113219947256),
 (95, 0.11078453247020953),
 (96, 0.023065080747191907),
 (97, 0.01876463657480421),
 (98, 0.01790453950761211),
 (99, 0.004752744667280449),
 (100, 0.022201264527760164),
 (101, 0.020491286653544993),
 (102, 0.05299036706929893),
 (103, 0.030681091359088915),
 (104, 0.012704785889300286),
 (105, 0.05499232862023555),
 (106, 0.017839338283756792),
 (107, 0.01669960969910606),
 (108, 0.08581951160386207),
 (109, 0.02146889262105555),
 (110, 0.013048733311027834),
 (111, 0.0693259414776503),
 (112, 0.01871391914720343),
 (113, 0.014078377718482723),
 (114, 0.014341831219085721),
 (115, 0.014295578954099608),
 (116, 0.013797241981461178),
 (117, 0.018024767650187092),
 (118, 0.011660938962146497),
 (119, 0.027476770713434524),
 (120, 0.0),
 (121, 0.032494583469984864),
 (122, 0.03558579627763736),
 (123, 0.04709889108117646),
 (124, 0.029113695500869428),
 (125, 0.03176916528953104),
 (126, 0.05188144860163879),
 (127, 0.06831921199014553),
 (128, 0.0),
 (129, 0.034538626305512035),
 (130, 0.006839958731550865),
 (131, 0.04061234621071931),
 (132, 0.019145118938687835),
 (133, 0.027388154657967036),
 (134, 0.06248127409030778),
 (135, 0.0),
 (136, 0.005538758856272572),
 (137, 0.019099918465186966),
 (138, 0.0451390933608319),
 (139, 0.05719692262180098),
 (140, 0.020383818716989074),
 (141, 0.04066039019610408),
 (142, 0.042740384900056105),
 (143, 0.028432337301670246),
 (144, 0.010739254488289603),
 (145, 0.004832342016477949),
 (146, 0.01322895328286413),
 (147, 0.012599888690093203),
 (148, 0.034065051096549066),
 (149, 0.10741645452119532),
 (150, 0.09681544154958377),
 (151, 0.09755957386449003),
 (152, 0.018975929881678517),
 (153, 0.03822885581390048),
 (154, 0.03242238632361453),
 (155, 0.013462488371653333),
 (156, 0.02650625501474838),
 (157, 0.035955487651922),
 (158, 0.07301803568521995),
 (159, 0.016329294067650397),
 (160, 0.056561644479559275),
 (161, 0.011894186782796549),
 (162, 0.005668557019499247),
 (163, 0.02639996986985608),
 (164, 0.018846829027470608),
 (165, 0.011344950448123278),
 (166, 0.05578107254777194),
 (167, 0.02368189774850944),
 (168, 0.1260247592504771),
 (169, 0.03693541009128285),
 (170, 0.054583684724411136),
 (171, 0.020319205912528924),
 (172, 0.0898483334311749),
 (173, 0.017215276527376557),
 (174, 0.02014365069733809),
 (175, 0.021687570238097868),
 (176, 0.007456340240947525),
 (177, 0.0),
 (178, 0.006535968126088083),
 (179, 0.04675682143508621),
 (180, 0.004271094502553953),
 (181, 0.012183227132496071),
 (182, 0.07004200085485725),
 (183, 0.028451570917252884),
 (184, 0.10642216669984642),
 (185, 0.016322671177462753),
 (186, 0.012421399034125376),
 (187, 0.0507664497199495),
 (188, 0.004367229875597695),
 (189, 0.06693465064254754),
 (190, 0.031748081418226375),
 (191, 0.015690695731592694),
 (192, 0.03217667982857704),
 (193, 0.041895725735215536),
 (194, 0.0),
 (195, 0.02041814369311641),
 (196, 0.014382901263823253),
 (197, 0.01393487046296578),
 (198, 0.019169211400809953),
 (199, 0.029398308447907927),
 (200, 0.034594736053038436),
 (201, 0.0),
 (202, 0.005560407504629118),
 (203, 0.018268562701864943),
 (204, 0.018769510116879662),
 (205, 0.03639564264156091),
 (206, 0.036125076496572255),
 (207, 0.02033181880990237),
 (208, 0.04084555376247849),
 (209, 0.034630933597322555),
 (210, 0.034401596704917804),
 (211, 0.009431665738389581),
 (212, 0.018246754448303912),
 (213, 0.023016149313544072),
 (214, 0.0),
 (215, 0.018162534946965583),
 (216, 0.01275181846971079),
 (217, 0.03560674869551733),
 (218, 0.007992821213379391),
 (219, 0.03946866708677197),
 (220, 0.12626142383501923),
 (221, 0.012669339546508078),
 (222, 0.04452284155313409),
 (223, 0.04575987982662422),
 (224, 0.029367249737344534),
 (225, 0.013420041437381378),
 (226, 0.00729664641099441),
 (227, 0.028501261363391907),
 (228, 0.05540461411124624),
 (229, 0.03583616819892439),
 (230, 0.03964687542612301),
 (231, 0.0),
 (232, 0.03036142192149118),
 (233, 0.02903966399282618),
 (234, 0.03564379284240509),
 (235, 0.03532952062644378),
 (236, 0.10393926581552604),
 (237, 0.013929430086047521),
 (238, 0.049307457565183614),
 (239, 0.08535197525542783),
 (240, 0.009745539691820678),
 (241, 0.020338404660784192),
 (242, 0.021355242918953993),
 (243, 0.03204200162158543),
 (244, 0.05436793627366309),
 (245, 0.02904840263672674),
 (246, 0.04744662194930338),
 (247, 0.0),
 (248, 0.009193131181781278),
 (249, 0.0778461882093143),
 (250, 0.0),
 (251, 0.03907646209188819),
 (252, 0.00401881450698247),
 (253, 0.02334353980446399),
 (254, 0.04277532237811697),
 (255, 0.0),
 (256, 0.04044881329323598),
 (257, 0.014704328340087575),
 (258, 0.006265487967399554),
 (259, 0.013646044848202959),
 (260, 0.14044486215018565),
 (261, 0.004525254495742668),
 (262, 0.04757140596817962),
 (263, 0.022569263070852608),
 (264, 0.0),
 (265, 0.010123102235483045),
 (266, 0.05791462840645881),
 (267, 0.01534103568703333),
 (268, 0.018400329731931016),
 (269, 0.020958385922386583),
 (270, 0.05357902847275625),
 (271, 0.01813237263169952),
 (272, 0.007355013149470557),
 (273, 0.003812875768059508),
 (274, 0.0467278398584456),
 (275, 0.09568756043268309),
 (276, 0.018561850370068925),
 (277, 0.02053364216383909),
 (278, 0.09013596002901834),
 (279, 0.0760014213972975),
 (280, 0.0),
 (281, 0.06599113864013725),
 (282, 0.05883621591156463),
 (283, 0.049796043538785216),
 (284, 0.004286423681671035),
 (285, 0.003960365687371271),
 (286, 0.05009220092665047),
 (287, 0.04479725855000052),
 (288, 0.015331120700760788),
 (289, 0.016060506847235523),
 (290, 0.014717948267847576),
 (291, 0.010698514875950428),
 (292, 0.02896236365523585),
 (293, 0.010528889732137474),
 (294, 0.0778936519258648),
 (295, 0.028553777317701597),
 (296, 0.010891771517402038),
 (297, 0.021153207293752106),
 (298, 0.0),
 (299, 0.01587703616803151),
 (300, 0.10530501293717727),
 (301, 0.044828704559220625),
 (302, 0.020031058391073477),
 (303, 0.004584959154514478),
 (304, 0.029008740877581724),
 (305, 0.11665304461770121),
 (306, 0.07157681090216014),
 (307, 0.05246721172862431),
 (308, 0.03638980476228088),
 (309, 0.018489997335654047),
 (310, 0.006556174193992921),
 (311, 0.1401718030391894),
 (312, 0.06940933849442626),
 (313, 0.04933497024060674),
 (314, 0.0),
 (315, 0.025115053080499883),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.03500750809263527),
 (320, 0.0054314238607730886),
 (321, 0.0),
 (322, 0.12342605849391139),
 (323, 0.00774802441194135),
 (324, 0.00547362124847724),
 (325, 0.03084588776350984),
 (326, 0.014419619279647963),
 (327, 0.010819656206333874),
 (328, 0.006729800379547946),
 (329, 0.022790274335735064),
 (330, 0.0359982756344882),
 (331, 0.044811363263897556),
 (332, 0.03782851608413307),
 (333, 0.022107660130118223),
 (334, 0.06361562091682155),
 (335, 0.01237312693500138),
 (336, 0.022028090003741067),
 (337, 0.018641703432514343),
 (338, 0.0),
 (339, 0.012559556469835304),
 (340, 0.010224780530345496),
 (341, 0.03845965317617487),
 (342, 0.10547515555377925),
 (343, 0.012054541100330649),
 (344, 0.005713170866446807),
 (345, 0.004566986724312349),
 (346, 0.015250832450519084),
 (347, 0.0),
 (348, 0.025376385705197017),
 (349, 0.02229870328261952),
 (350, 0.011131090970738042),
 (351, 0.0),
 (352, 0.007243028919314596),
 (353, 0.017610941313975004),
 (354, 0.012565726413465322),
 (355, 0.007138144730165911),
 (356, 0.05267058270046675),
 (357, 0.0),
 (358, 0.018075600668062387),
 (359, 0.008708008220919525),
 (360, 0.007975105272938534),
 (361, 0.03566690142833676),
 (362, 0.04757813966597105),
 (363, 0.04688052447407405),
 (364, 0.010778432913261509),
 (365, 0.046381554675201886),
 (366, 0.01677505053759253),
 (367, 0.0),
 (368, 0.07403748614191069),
 (369, 0.10457996298424717),
 (370, 0.01246161288011445),
 (371, 0.024668445607216927),
 (372, 0.02184097807868396),
 (373, 0.13104327541673755),
 (374, 0.006859645508735325),
 (375, 0.04654563010018715),
 (376, 0.02430995471005437),
 (377, 0.0),
 (378, 0.0),
 (379, 0.010998855175162718),
 (380, 0.023231962238113503),
 (381, 0.026173587527733185),
 (382, 0.0),
 (383, 0.032070630146859326),
 (384, 0.0068237784570519145),
 (385, 0.0),
 (386, 0.004493991544369328),
 (387, 0.004921612254572531),
 (388, 0.0),
 (389, 0.03566371639169199),
 (390, 0.008891529598522765),
 (391, 0.01792528360198157),
 (392, 0.006505533099880023),
 (393, 0.0),
 (394, 0.004813071324547192),
 (395, 0.013013764940898193),
 (396, 0.012298725910680916),
 (397, 0.013610871753023885),
 (398, 0.0),
 (399, 0.005421292988934254),
 (400, 0.027165480889111714),
 (401, 0.022831362663742583),
 (402, 0.022784484518299924),
 (403, 0.02309885999000056),
 (404, 0.051158310130733985),
 (405, 0.023099367975103518),
 (406, 0.01273524977002642),
 (407, 0.0075511619731115),
 (408, 0.006206011872639049),
 (409, 0.0),
 (410, 0.03948336431921645),
 (411, 0.011326962329371061),
 (412, 0.06572783211093389),
 (413, 0.0375831884075777),
 (414, 0.00859389910465831),
 (415, 0.027084421507941252),
 (416, 0.0165539172882658),
 (417, 0.009364769850806061),
 (418, 0.027619705282526386),
 (419, 0.02229367445355622),
 (420, 0.046922797885632),
 (421, 0.009246350053487031),
 (422, 0.07562406084979008),
 (423, 0.03957817520415513),
 (424, 0.00806111539631988),
 (425, 0.024392461700156635),
 (426, 0.01805801180882475),
 (427, 0.006182077540290648),
 (428, 0.01386292556096647),
 (429, 0.0),
 (430, 0.04671279876481353),
 (431, 0.009401440499931949),
 (432, 0.07813788987731421),
 (433, 0.006901247756804691),
 (434, 0.0),
 (435, 0.013088089558802496),
 (436, 0.0),
 (437, 0.0052288129356324025),
 (438, 0.1495197109967932),
 (439, 0.04178421244245015),
 (440, 0.005318866444720196),
 (441, 0.02223765130901368),
 (442, 0.012775379071644603),
 (443, 0.024055614011451107),
 (444, 0.0),
 (445, 0.03965909807875144),
 (446, 0.004522180410255011),
 (447, 0.016823517491310315),
 (448, 0.021113777016166065),
 (449, 0.061945007945727215),
 (450, 0.021041569608077335),
 (451, 0.03775577554174588),
 (452, 0.011802936098887901),
 (453, 0.004467350949967132),
 (454, 0.07314060419058777),
 (455, 0.03522847797177335),
 (456, 0.018513278894412333),
 (457, 0.02218167280155911),
 (458, 0.01692058231311489),
 (459, 0.008044968625006322),
 (460, 0.006939743424605071),
 (461, 0.09553077960521641),
 (462, 0.02067540085102302),
 (463, 0.007509847266968145),
 (464, 0.0),
 (465, 0.0),
 (466, 0.05936460664510532),
 (467, 0.04065207719240804),
 (468, 0.005570040285503978),
 (469, 0.02457010244276022),
 (470, 0.014348374275298888),
 (471, 0.021733273852838207),
 (472, 0.044109780770574994),
 (473, 0.05319980978534787),
 (474, 0.0),
 (475, 0.00999452766843397),
 (476, 0.1132793909178202),
 (477, 0.0),
 (478, 0.017550463908769014),
 (479, 0.05957739519036156),
 (480, 0.05378333648765774),
 (481, 0.0),
 (482, 0.007485755247119568),
 (483, 0.04347838302543515),
 (484, 0.008152712150884934),
 (485, 0.016091518180316795),
 (486, 0.03618721493981977),
 (487, 0.06727091871418366),
 (488, 0.036613978239909445),
 (489, 0.0),
 (490, 0.036152945010714616),
 (491, 0.042566046224616974),
 (492, 0.04804046552079769),
 (493, 0.011127487423321165),
 (494, 0.0),
 (495, 0.09270428844881938),
 (496, 0.0),
 (497, 0.0),
 (498, 0.01734187180803409),
 (499, 0.0),
 (500, 0.004540776703736457),
 (501, 0.037049092547785455),
 (502, 0.09373860649716101),
 (503, 0.017451647150999904),
 (504, 0.0),
 (505, 0.05790886230665173),
 (506, 0.026952792010475134),
 (507, 0.15094607753762165),
 (508, 0.0493117270526214),
 (509, 0.005733522558537745),
 (510, 0.055574686985795645),
 (511, 0.02333702475579217),
 (512, 0.005411059907998344),
 (513, 0.13874601022353342),
 (514, 0.01113940910872116),
 (515, 0.005883516446944649),
 (516, 0.006995633672759897),
 (517, 0.0),
 (518, 0.010002196148115653),
 (519, 0.0),
 (520, 0.0),
 (521, 0.005710471440526881),
 (522, 0.008631123558313945),
 (523, 0.011016553928537861),
 (524, 0.0),
 (525, 0.012166601357148078),
 (526, 0.008912694510692607),
 (527, 0.008823663645717392),
 (528, 0.00410857567116767),
 (529, 0.1298760410304624),
 (530, 0.014990836356798586),
 (531, 0.010500072785557533),
 (532, 0.019896087619016612),
 (533, 0.029721895851862443),
 (534, 0.022097624170640998),
 (535, 0.053724887044767175),
 (536, 0.04466707553259569),
 (537, 0.019137344843416726),
 (538, 0.0),
 (539, 0.154385956613235),
 (540, 0.025729714594420014),
 (541, 0.0797594266623036),
 (542, 0.009981454025970445),
 (543, 0.03163768452050671),
 (544, 0.012377084440302956),
 (545, 0.010056587102863529),
 (546, 0.03149179594973153),
 (547, 0.026233594867920783),
 (548, 0.0),
 (549, 0.10798119001670278),
 (550, 0.01621090210824575),
 (551, 0.008846534983575693),
 (552, 0.0),
 (553, 0.00639412867782083),
 (554, 0.0),
 (555, 0.052494681526726227),
 (556, 0.005017879793225572),
 (557, 0.14034152788902235),
 (558, 0.0),
 (559, 0.007677899427446597),
 (560, 0.008858250714464267),
 (561, 0.008377134853793806),
 (562, 0.006692788191157282),
 (563, 0.04187806320279708),
 (564, 0.055192284473698894),
 (565, 0.010493326834883344),
 (566, 0.005893239973795194),
 (567, 0.006437006288063359),
 (568, 0.0770385113965675),
 (569, 0.01742603884821685),
 (570, 0.050248366901766976),
 (571, 0.021872743360688188),
 (572, 0.0401181706902702),
 (573, 0.0038848417568546905),
 (574, 0.004693307614311773),
 (575, 0.01602315704447708),
 (576, 0.0348870167801318),
 (577, 0.10088596242039377),
 (578, 0.017793867336476275),
 (579, 0.08868064515479893),
 (580, 0.004610895700177417),
 (581, 0.0747447454115543),
 (582, 0.20224698563993562),
 (583, 0.015233562116362467),
 (584, 0.029487216838505446),
 (585, 0.01405547498708008),
 (586, 0.010068794898541338),
 (587, 0.05978614039665892),
 (588, 0.01783441985805471),
 (589, 0.058003171327803804),
 (590, 0.006495434845045867),
 (591, 0.022556835228415974),
 (592, 0.006008717130107083),
 (593, 0.0),
 (594, 0.010825873709918025),
 (595, 0.13397692345524476),
 (596, 0.032619416686951605),
 (597, 0.03576252412638119),
 (598, 0.010130371824518402),
 (599, 0.01840247780098415),
 (600, 0.01744288505345107),
 (601, 0.009291840748149354),
 (602, 0.04446142738191835),
 (603, 0.009302005411450813),
 (604, 0.013622718838456161),
 (605, 0.014048124059273043),
 (606, 0.0),
 (607, 0.02660074404598287),
 (608, 0.015381136138621384),
 (609, 0.01437450426035429),
 (610, 0.018712479019275505),
 (611, 0.004063616926179041),
 (612, 0.01678908351888396),
 (613, 0.0073365132026175246),
 (614, 0.06653548588001257),
 (615, 0.032288237521129436),
 (616, 0.019106086316630282),
 (617, 0.04209751608609604),
 (618, 0.026469665833993024),
 (619, 0.0),
 (620, 0.0),
 (621, 0.03331318621224231),
 (622, 0.0038929584720316006),
 (623, 0.0),
 (624, 0.04871743625168264),
 (625, 0.007075028765331364),
 (626, 0.051370965524734614),
 (627, 0.028178734485501497),
 (628, 0.0),
 (629, 0.02526925953234315),
 (630, 0.006413315853708386),
 (631, 0.012641527377948422),
 (632, 0.06179980263467967),
 (633, 0.004381323613036875),
 (634, 0.040660234185177085),
 (635, 0.06342730514044691),
 (636, 0.009997956762941051),
 (637, 0.006062434699312702),
 (638, 0.007829318291592854),
 (639, 0.0),
 (640, 0.02574554589826808),
 (641, 0.0),
 (642, 0.0),
 (643, 0.06884615541018681),
 (644, 0.012440432164436717),
 (645, 0.008987314838282879),
 (646, 0.04723191870021918),
 (647, 0.07009500113698139),
 (648, 0.007553961570715532),
 (649, 0.0),
 (650, 0.05014170269784576),
 (651, 0.0),
 (652, 0.012787638967699477),
 (653, 0.045247464504872575),
 (654, 0.03296239863294855),
 (655, 0.004399837740513799),
 (656, 0.0),
 (657, 0.008811963552313784),
 (658, 0.013496376346932848),
 (659, 0.005545872152476312),
 (660, 0.02459271318527169),
 (661, 0.09088613957817657),
 (662, 0.0),
 (663, 0.0),
 (664, 0.016678339019956225),
 (665, 0.015104088549940674),
 (666, 0.040956211027471864),
 (667, 0.0),
 (668, 0.06765750990007269),
 (669, 0.03031825727996446),
 (670, 0.00436774552251118),
 (671, 0.03082443602443767),
 (672, 0.01129635561607157),
 (673, 0.029253278159695712),
 (674, 0.06967118450971524),
 (675, 0.04482360008393575),
 (676, 0.006197966206780936),
 (677, 0.004560438205232394),
 (678, 0.052925349983800524),
 (679, 0.0),
 (680, 0.03843782519436603),
 (681, 0.006613755964443661),
 (682, 0.006097651037896674),
 (683, 0.010503639652365046),
 (684, 0.0),
 (685, 0.006704731123979335),
 (686, 0.01106725266260676),
 (687, 0.04730480006912536),
 (688, 0.022732987744289217),
 (689, 0.0),
 (690, 0.009258144377784636),
 (691, 0.013069846094658296),
 (692, 0.08093516028545063),
 (693, 0.013670152127438773),
 (694, 0.00444611970978278),
 (695, 0.014469052976248117),
 (696, 0.01358768252145893),
 (697, 0.0),
 (698, 0.013880221628336794),
 (699, 0.014735762487947644),
 (700, 0.0057244044446017476),
 (701, 0.03853068082694543),
 (702, 0.004395081870659723),
 (703, 0.004539029691339267),
 (704, 0.043265036967991125),
 (705, 0.005649000095530291),
 (706, 0.019160050886225813),
 (707, 0.0),
 (708, 0.0045723413037214765),
 (709, 0.007872495817086005),
 (710, 0.027761546237164692),
 (711, 0.015248130776601239),
 (712, 0.0),
 (713, 0.006739809042371471),
 (714, 0.0),
 (715, 0.028278948710418417),
 (716, 0.006333920349172367),
 (717, 0.0),
 (718, 0.03038231386075742),
 (719, 0.0),
 (720, 0.021385171136208102),
 (721, 0.009106242397741765),
 (722, 0.0),
 (723, 0.008901130662783634),
 (724, 0.004665447724664726),
 (725, 0.0),
 (726, 0.0),
 (727, 0.006788690501158126),
 (728, 0.02286483338539308),

In [119]:
def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])[1:6]
    for i in distances:
        print(new_df.iloc[i[0]].title)

In [121]:
recommend("Batman Begins")

The Dark Knight Rises
The Dark Knight
Batman
Batman Returns
Batman v Superman: Dawn of Justice

In [123]:
import pickle
pickle.dump(new_df,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))